apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end-all
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-end-all
  template:
    metadata:
      labels:
        app: front-end-all
    spec:
      containers:
        - name: front-end-all
          image: justinzhang7183/fullstack-frontend-all
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: front-end-all
  namespace: default
spec:
  type: NodePort
  selector:
    app: front-end-all
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000